### PR TITLE
Fix AsyncSeq.cache #33

### PR DESCRIPTION
**Pull request by eulerfx**
This fixes the issue in #33 but warrants additional discussion wrt the wait strategy.

### CODE REVIEW

**Comment by dsyme** [comment]
Could you add some tests for this too that expose the original problem? thanks

**Comment by eulerfx** [comment]
Sure, the test is included in the [commit](https://github.com/eulerfx/FSharp.Control.AsyncSeq/commit/66f61c7e46e191df5bd903ce69aad192487913d5) and also noted here: https://github.com/fsprojects/FSharp.Control.AsyncSeq/issues/33#issuecomment-137778655

**Comment by dsyme** [comment]
Ah yes, sorry, I'm blind

**Comment by dsyme** [comment]
@eulerfx Could you release a new nuget package?

**Pull request merged**
