### PR TITLE
Implemented ofIQueryable according to EF Core implementation

### PR DESCRIPTION
**Pull request by xperiandri**
https://github.com/dotnet/efcore/blob/2795a00b613a5f4f23fca4ad1c53012d17adf7d3/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs#L2927

Also removed trailing whitespaces

### CODE REVIEW

**Comment by xperiandri** [comment]
I haven't added any tests as it requires creating some IQueryable implementation like EF Core model

**Comment by dsyme** [comment]
This is great, thanks

I'll merge.  Can you also submit an editorconfig file to keep the removal of end of line whitespace?

**Comment by xperiandri** [comment]
@dsyme like that?

**Comment by xperiandri** [comment]
Or use `utf-8-bom` for all files?

**Comment by dsyme** [comment]
It's ok I think!

**Pull request merged**
