### PR TITLE
move to fsdocs

### PR DESCRIPTION
**Pull request by dsyme**

### CODE REVIEW

**Comment by dsyme** [comment]
cc @eiriktsarpalis 

I will push a new version of the tool that automatically copies these files from the nuget package:

    C:\Users\dsyme\.nuget\packages\fsharp.formatting.commandtool\6.0.7\styles

image

**Comment by eiriktsarpalis** [comment]
Hi @dsyme, I was trying to port my libs to the latest fsdocs, but there doesn't seem to be a clear way for generating API references. I tried running this AsyncSeq build and it looks like it doens't generate an API reference either?

**Comment by dsyme** [comment]
@eiriktsarpalis Hmmmm...  Do you mean cross references or this? http://fsprojects.github.io/FSharp.Control.AsyncSeq/reference/index.html

**Comment by dsyme** [comment]
Hmmm the docs at http://fsprojects.github.io/FSharp.Control.AsyncSeq/reference/index.html don't actually seem to have been updated.  I will check

**Comment by dsyme** [comment]
@eiriktsarpalis OK the docs are updated.  Still not sure what you meant by this?  Is it cross-references?

**Comment by eiriktsarpalis** [comment]
When I checked it was serving an empty document. Which is what I was getting in my own library when trying to port it, so it isn't clear to me how I can generate them using the cli tool.

**Comment by dsyme** [comment]
> When I checked it was serving an empty document. Which is what I was getting in my own library when trying to port it, so it isn't clear to me how I can generate them using the cli tool.


Could you send a log?

So one thing I noticed that may be what you're seeing is that `dotnet watch` is serving an error for `locahost/index.html` when there is no `index.md/fsx` in `docs`, i.e. there are no literate docs and you're just generating reference docs.  In this case look for `localhost/reference/index.html`.  Also check `tmp/watch/reference/index.html`

So do you have a `docs/index.md` or `docs/index.fsx`?

**Comment by eiriktsarpalis** [comment]
There is an `docs/index.fsx`, the [WIP changes are here](https://github.com/eiriktsarpalis/Argu/tree/fdocs-unfinished).

```
$ dotnet fsdocs build
restored project state from '.fsdocs/cache'
parameter project-name = Argu
parameter root = http://fsprojects.github.io/Argu/
parameter authors = Eirik Tsarpalis
parameter repository-url = https://github.com/fsprojects/Argu/
parameter repository-branch =
parameter repository-type = git
parameter package-license = MIT
parameter package-icon-url =
parameter package-tags = F#, argument, parser
parameter package-version = 1.0.0
parameter repository-commit =
parameter copyright = 2019
repoBranchOption = Some ""
using extra content from C:\Users\eitsarpa\.nuget\packages\fsharp.formatting.commandtool\6.1.0\extras
converting docs\index.fsx --> C:\Users\eitsarpa\devel\public\Argu\output\index.html
converting docs\perf.fsx --> C:\Users\eitsarpa\devel\public\Argu\output\perf.html
converting docs\tutorial.fsx --> C:\Users\eitsarpa\devel\public\Argu\output\tutorial.html
skipping directory docs\.fsdocs
skipping directory docs\.ionide
copying docs\img\fsharp.png --> C:\Users\eitsarpa\devel\public\Argu\output\img\fsharp.png
copying docs\img\logo.pdn --> C:\Users\eitsarpa\devel\public\Argu\output\img\logo.pdn
copying docs\img\logo.png --> C:\Users\eitsarpa\devel\public\Argu\output\img\logo.png
copying docs\img\nessos.png --> C:\Users\eitsarpa\devel\public\Argu\output\img\nessos.png
copying docs\output\index.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\index.html
copying docs\output\perf.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\perf.html
copying docs\output\tutorial.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\tutorial.html
copying docs\output\content\style.css --> C:\Users\eitsarpa\devel\public\Argu\output\output\content\style.css
copying docs\output\content\style_light.css --> C:\Users\eitsarpa\devel\public\Argu\output\output\content\style_light.css
copying docs\output\content\tips.js --> C:\Users\eitsarpa\devel\public\Argu\output\output\content\tips.js
copying docs\output\content\img\github-blue.png --> C:\Users\eitsarpa\devel\public\Argu\output\output\content\img\github-blue.png
copying docs\output\content\img\github.png --> C:\Users\eitsarpa\devel\public\Argu\output\output\content\img\github.png
copying docs\output\img\fsharp.png --> C:\Users\eitsarpa\devel\public\Argu\output\output\img\fsharp.png
copying docs\output\img\logo.pdn --> C:\Users\eitsarpa\devel\public\Argu\output\output\img\logo.pdn
copying docs\output\img\logo.png --> C:\Users\eitsarpa\devel\public\Argu\output\output\img\logo.png
copying docs\output\img\nessos.png --> C:\Users\eitsarpa\devel\public\Argu\output\output\img\nessos.png
copying docs\output\reference\argu-appsettingsconfigurationreader.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-appsettingsconfigurationreader.html
copying docs\output\reference\argu-arguattributes-altcommandlineattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-altcommandlineattribute.html
copying docs\output\reference\argu-arguattributes-appsettingsseparatorattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-appsettingsseparatorattribute.html
copying docs\output\reference\argu-arguattributes-clipositionattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-clipositionattribute.html
copying docs\output\reference\argu-arguattributes-cliprefixattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-cliprefixattribute.html
copying docs\output\reference\argu-arguattributes-colonassignmentattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-colonassignmentattribute.html
copying docs\output\reference\argu-arguattributes-colonassignmentorspacedattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-colonassignmentorspacedattribute.html
copying docs\output\reference\argu-arguattributes-customappsettingsattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-customappsettingsattribute.html
copying docs\output\reference\argu-arguattributes-customassignmentattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-customassignmentattribute.html
copying docs\output\reference\argu-arguattributes-customassignmentorspacedattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-customassignmentorspacedattribute.html
copying docs\output\reference\argu-arguattributes-customcommandlineattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-customcommandlineattribute.html
copying docs\output\reference\argu-arguattributes-disablehelpflagsattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-disablehelpflagsattribute.html
copying docs\output\reference\argu-arguattributes-equalsassignmentattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-equalsassignmentattribute.html
copying docs\output\reference\argu-arguattributes-equalsassignmentorspacedattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-equalsassignmentorspacedattribute.html
copying docs\output\reference\argu-arguattributes-exactlyonceattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-exactlyonceattribute.html
copying docs\output\reference\argu-arguattributes-firstattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-firstattribute.html
copying docs\output\reference\argu-arguattributes-gatherallsourcesattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-gatherallsourcesattribute.html
copying docs\output\reference\argu-arguattributes-gatherunrecognizedattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-gatherunrecognizedattribute.html
copying docs\output\reference\argu-arguattributes-helpdescriptionattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-helpdescriptionattribute.html
copying docs\output\reference\argu-arguattributes-helpflagsattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-helpflagsattribute.html
copying docs\output\reference\argu-arguattributes-hiddenattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-hiddenattribute.html
copying docs\output\reference\argu-arguattributes-inheritattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-inheritattribute.html
copying docs\output\reference\argu-arguattributes-lastattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-lastattribute.html
copying docs\output\reference\argu-arguattributes-maincommandattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-maincommandattribute.html
copying docs\output\reference\argu-arguattributes-mandatoryattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-mandatoryattribute.html
copying docs\output\reference\argu-arguattributes-noappsettingsattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-noappsettingsattribute.html
copying docs\output\reference\argu-arguattributes-nocommandlineattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-nocommandlineattribute.html
copying docs\output\reference\argu-arguattributes-parsecsvattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-parsecsvattribute.html
copying docs\output\reference\argu-arguattributes-printlabelsattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-printlabelsattribute.html
copying docs\output\reference\argu-arguattributes-requiresubcommandattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-requiresubcommandattribute.html
copying docs\output\reference\argu-arguattributes-restattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-restattribute.html
copying docs\output\reference\argu-arguattributes-subcommandattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-subcommandattribute.html
copying docs\output\reference\argu-arguattributes-uniqueattribute.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes-uniqueattribute.html
copying docs\output\reference\argu-arguattributes.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguattributes.html
copying docs\output\reference\argu-arguexception.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguexception.html
copying docs\output\reference\argu-argumentcaseinfo.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-argumentcaseinfo.html
copying docs\output\reference\argu-argumentparser-1.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-argumentparser-1.html
copying docs\output\reference\argu-argumentparser.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-argumentparser.html
copying docs\output\reference\argu-argumentparserutils.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-argumentparserutils.html
copying docs\output\reference\argu-argumenttype.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-argumenttype.html
copying docs\output\reference\argu-arguparseexception.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-arguparseexception.html
copying docs\output\reference\argu-cliposition.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-cliposition.html
copying docs\output\reference\argu-cliprefix.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-cliprefix.html
copying docs\output\reference\argu-configurationreader.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-configurationreader.html
copying docs\output\reference\argu-customassignmentseparator.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-customassignmentseparator.html
copying docs\output\reference\argu-dictionaryconfigurationreader.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-dictionaryconfigurationreader.html
copying docs\output\reference\argu-environmentvariableconfigurationreader.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-environmentvariableconfigurationreader.html
copying docs\output\reference\argu-errorcode.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-errorcode.html
copying docs\output\reference\argu-exceptionexiter.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-exceptionexiter.html
copying docs\output\reference\argu-functionconfigurationreader.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-functionconfigurationreader.html
copying docs\output\reference\argu-iargparsertemplate.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-iargparsertemplate.html
copying docs\output\reference\argu-iargumentparservisitor-1.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-iargumentparservisitor-1.html
copying docs\output\reference\argu-iconfigurationreader.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-iconfigurationreader.html
copying docs\output\reference\argu-iexiter.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-iexiter.html
copying docs\output\reference\argu-nullconfigurationreader.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-nullconfigurationreader.html
copying docs\output\reference\argu-parseresults-1.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-parseresults-1.html
copying docs\output\reference\argu-parsesource.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-parsesource.html
copying docs\output\reference\argu-processexiter.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\argu-processexiter.html
copying docs\output\reference\index.html --> C:\Users\eitsarpa\devel\public\Argu\output\output\reference\index.html
copying C:\Users\eitsarpa\.nuget\packages\fsharp.formatting.commandtool\6.1.0\extras\Dockerfile --> C:\Users\eitsarpa\devel\public\Argu\output\Dockerfile
copying C:\Users\eitsarpa\.nuget\packages\fsharp.formatting.commandtool\6.1.0\extras\NuGet.config --> C:\Users\eitsarpa\devel\public\Argu\output\NuGet.config
copying C:\Users\eitsarpa\.nuget\packages\fsharp.formatting.commandtool\6.1.0\extras\content\fsdocs-search.js --> C:\Users\eitsarpa\devel\public\Argu\output\content\fsdocs-search.js
copying C:\Users\eitsarpa\.nuget\packages\fsharp.formatting.commandtool\6.1.0\extras\content\fsdocs-style.css --> C:\Users\eitsarpa\devel\public\Argu\output\content\fsdocs-style.css
copying C:\Users\eitsarpa\.nuget\packages\fsharp.formatting.commandtool\6.1.0\extras\content\fsdocs-tips.js --> C:\Users\eitsarpa\devel\public\Argu\output\content\fsdocs-tips.js
copying C:\Users\eitsarpa\.nuget\packages\fsharp.formatting.commandtool\6.1.0\extras\img\content\github-blue.png --> C:\Users\eitsarpa\devel\public\Argu\output\img\content\github-blue.png
copying C:\Users\eitsarpa\.nuget\packages\fsharp.formatting.commandtool\6.1.0\extras\img\content\github.png --> C:\Users\eitsarpa\devel\public\Argu\output\img\content\github.png
sourceFolder = C:\Users\eitsarpa\devel\public\Argu
sourceRepo = Some "https://github.com/fsprojects/Argu//tree/master"
Generating output\reference\index.html
```

The issue is that `output/reference/index.html` does not contain any API references, which probably makes sense, it is not clear how to specify which DLLs need to be documented.

**Comment by dsyme** [comment]
> The issue is that output/reference/index.html does not contain any API references, which probably makes sense, it is not clear how to specify which DLLs need to be documented.

No namespaces?  This is strange. At least one namespace should be shown like this.  Something must be different http://fsprojects.github.io/FSharp.Control.AsyncSeq//reference/index.html

**Comment by eiriktsarpalis** [comment]
I'm not longer reproducing the issue. I didn't make any changes so I'm assuming it must have been local state. Apologies for the confusion.

**Pull request merged**
