### PR TITLE
More tests on takeUntilSignal and skipUntilSignal

### PR DESCRIPTION
**Pull request by xkrt**
Only edge cases was tested

### CODE REVIEW

**Comment by dsyme** [comment]
Great - is the failing test uncovering a bug, or is it just timing on the cloud VMs?

**Comment by xkrt** [comment]
@dsyme looks like just timing on AppVeyor. Not sure: increase sleeps or insert some synchronization code.

**Comment by dsyme** [comment]
Just increase the sleeps I think

**Comment by eulerfx** [comment]
Looks like the AppVeyor build failed last time. Did increasing the timeouts do the trick?

**Pull request closed without merging**
