### PR TITLE
release notes v2.0.3

### PR DESCRIPTION
**Pull request by eulerfx**

### CODE REVIEW

**Comment by eulerfx** [comment]
@dsyme I don't think I've the access to publish the nuget package, but this PR has the release notes and version update.

**Comment by dsyme** [comment]
Urgh, two heisen failures on Mono: https://s3.amazonaws.com/archive.travis-ci.org/jobs/94729006/log.txt

**Comment by dsyme** [comment]
If someone has time to look into those failures it would be much appreciated...

**Comment by dsyme** [comment]
@eulerfx You have permission for https://www.nuget.org/packages/FSharp.Control.AsyncSeq/

**Pull request merged**
