### PR TITLE
Move to AsyncSeq = IAsyncEnumerable to fix #15

### LINKED ISSUE #15: Resources, AsyncSeq, Try Finally and possible alternative definitions
In general we expect sensible behaviour for sub-sequences of AsyncSeq objects (those returned by tail, skip etc.) 

When I look at the definition of something like ``ofObservableUsingAgent `` I see an AsyncSeq which has internal resources - an agent - and, if you replayed the_tail_ of the sequence multiple times, or if you didn't iterate all the way through the sequence, then you'd get some odd behaviour - each time you're replying it you're communicating with the agent and presumably getting different replies. The agent allocated at the start represents shared state, shared between all the various sub-sequences returned. Also, the agent only gets collected if the sequence gets iterated all the way to the end.

  let internal ofObservableUsingAgent (input : System.IObservable<_>) f = 
    asyncSeq {  
      use agent = AutoCancelAgent.Start(f)
      ...
      yield! loop() }

All this stems from the fact that the definition of AsyncSeq is currently much like a lazy list, just asynchronous (indeed it's name could almost be AsyncList).  The "tail" operation drops the head, and a "cons" would put a different head on etc.  Attempts to use shared mutable resources in LazyList-like combinators usually results them being shared in all "tail" instances, with odd results.  

Basically, LazyList-like structures can't hold shared-mutable or disposable resources during iteration.  That's one advantage of ``IEnumerable<'T>`` over ``LazyList<'T>``, because IEnumerable separates iteration from data, and iterators can hold state.

To give another example, the current "algebraic" definition is problematic w.r.t. the behaviour of  "use" .  As things stand today, when you use "use" in an ``asyncSeq { ... }`` 

(a) The compensation functions are only executed if the consuming iteration completes to the _end_ of the sequence - and not if an early exit occurs.  (In contrast, IEnumerator objects can be disposed at any point during the iteration.)

(b) The compensation functions will be executed every time the "tail" of an async seq is iterated to its end.  (In contrast, a separate IEnumerator object is created for each iteration.)

Basically, it's probably not a good idea to try have both an algebraic definition of AsyncSeq _and_ support using/try-finally.

All these problems leads to the possible alternative definition of AsyncSeq as an async version of iterators:

      type IAsyncEnumerator<'T> = 
          abstract MoveNext : Async<bool>
          abstract Current : 'T
          abstract Dispose : unit -> unit  (* or Async<unit> *)

      type IAsyncEnumerable<'T> = 
          abstract GetEnumerator : unit -> IAsyncEnumerator<'T>

      type AsyncSeq<'T> = IAsyncEnumerable<'T>

I actually think we need to do a comparison between the current "algebraic" definition of AsyncSeq and alternative "iterator" definitions. The iterator definition is in many ways the "natural" definition of asynchronous sequences for F#, at least if you take "sequence" = "iterable".  

In particular, the "iterator" definition allows a sensible notion of "Dispose" on the iterators, which allows them to have resource - very similarly to the case above.

Note that APIs can often have problems like this without them being observed as a significant problem in practice because in most cases AsyncSeq objects are one-shot - they are only ever iterated once, or iterations of the outermost object are independent as for Seq.  

Cheers
Don

### PR DESCRIPTION
**Pull request by dsyme**
A discussed in #15 we are moving to an implementation where AsyncSeq = IAsyncEnumerable, where an imperative asynchronous iterator is used to traverse sequences.  These sequences are disposable.

This implements this change. It's a nontrivial change, and the implementations of the enumerables are annoyingly imperative (they are based on the corresponding F# sequence implementation code).

The change also adds some new combinators and renames some others, see the AsyncSeq.fsi changes for details.

### CODE REVIEW

**Comment by tpetricek** [comment]
We talked about this, and I suppose the changes are OK.
Though it shows why I was reluctant - pretty much all the functions are now way more ugly and complicated... :-)

My only worry is that there are already things on the internet written about "async seq" using the old programming model. So, switching to a completely different implementation without calling it differently might be confusing. I agree "async seq" is good name for the current one (the previous should have been called "async list" or something), but I still wonder if it would be better to rename things here to avoid confusion...

**Comment by eulerfx** [comment]
A quick benchmark seems to show that the imperative version needs perf attention indeed. This code:

```fsharp
  Seq.init 10000 id
  |> AsyncSeq.ofSeq
  |> AsyncSeq.iterAsync (fun _ -> Async.empty)
```

- Release
- Fsi.exe
- MPB i7 Parallels/Windows 8.1

## IAsyncEnumerable

> Real: 00:00:25.341, CPU: 00:00:26.734, GC gen0: 353, gen1: 300, gen2: 1

## Algebraic 

> Real: 00:00:00.058, CPU: 00:00:00.046, GC gen0: 0, gen1: 0, gen2: 0

Looks like all the calls to the new internal `make` from `AsyncSeq.ofSeq` could be the culprit. Will take a look.

**Comment by dsyme** [comment]
Thanks, yes, we need to get this up to scratch.  Failing that we need to keep the algebraic version available (though probably renamed to AsyncList).

**Comment by dsyme** [comment]
@tpetricek - I'm not too worried about the old teaching material - I think it can be adjusted.  AsyncList seems like the right name for the algebraic version.

**Comment by dsyme** [comment]
Hi @eulerfx , could you take a look now?  The AsyncSeq.ofSeq implementation (using .For) seems to have been quadtratic - on sizes 5000 it is now 5000x faster.

If you could continue to stress test all the operators that would bee really great - given the intrinsic perf difference between List and Seq, we can I suppose expect an intrinsic difference between AsyncList and AsyncSeq too, but it would be good to minimize the difference and get it measured  

If you could submit perf tests (adhoc or otherwise) to the branch https://github.com/dsyme/FSharp.Control.AsyncSeq/tree/async-enum to form part of this PR I'd be immensely grateful.

**Comment by dsyme** [comment]
@eulerfx I added some performance comparisons with the old version (1.15.0) here: https://github.com/fsprojects/FSharp.Control.AsyncSeq/commit/b0c28d39e7f5328db4bf52ac87e31060d448113d#diff-18eb9da5348653d3d95202baec988c18R723.  It looks like things are generally faster.  I believe "AsyncSeq.map" and friends can all be made faster as well though.

**Pull request merged**
