### PR TITLE
Fable support

### LINKED ISSUE #110: Fable support?
As it stands now, it this library does not seem to support Fable. According to [the Fable docs](https://fable.io/docs/your-fable-project/author-a-fable-library.html), it is quite simple to add by modifying the project file:

```xml
<!-- Add source files to "fable" folder in Nuget package -->
<ItemGroup>
    <Content Include="*.fsproj; **\*.fs" PackagePath="fable\" />
</ItemGroup>
```

Is Fable support something that would be accepted in a PR?

### PR DESCRIPTION
**Pull request by Shmew**
Adds Fable support.

These all either make use of tasks, or each other. Unless I were to try to shadow `Task`, `TaskCompletionSource`, `AsyncAwaitTask`, and anything else I'm forgetting that these use they aren't able to be supported. Everything else has unit tests in the `tests/fable` directory.

One thing I could use some input on is that due to the nature of javascript some of these may be able to be simplified into a usable state for Fable (of course using a compiler directive to not change normal behavior).

* iterAsyncParallel
* iterAsyncParallelThrottled
* toBlockingSeq
* cache
* combineLatestWithAsync
* combineLatestWith
* combineLatest
* takeUntilSignal
* skipUntilSignal
* bufferByCountAndTime
* bufferByTime
* mergeChoice
* merge
* mergeAll
* mapAsyncParallel
* groupByAsync
* groupBy
* ofAsyncEnum
* toAsyncEnum
* Seq.ofAsyncSeq
* AsyncSeqSrc<'T>

Resolves #110

### CODE REVIEW

**Comment by TheAngryByrd** [comment]
If you didn't want to have to maintain two separate sets of tests, you could use Expecto and [Fable.Mocha](https://github.com/Zaid-Ajaj/Fable.Mocha#running-the-tests-on-dotnet-with-expecto).

**Comment by Shmew** [comment]
> If you didn't want to have to maintain two separate sets of tests, you could use Expecto and [Fable.Mocha](https://github.com/Zaid-Ajaj/Fable.Mocha#running-the-tests-on-dotnet-with-expecto).

A bulk of the tests needed to be re-written in a way that worked with Fable as pretty much all of them are using things like `Async.RunSynchronously`. In addition to defining a lot of helpers that Jest comes with ootb, especially things like [this](https://github.com/Shmew/FSharp.Control.AsyncSeq/blob/fable-support/tests/fable/FSharp.Control.AsyncSeq.Tests/AsyncSeq.test.fs#L919).

**Comment by Shmew** [comment]
@wilsoncg @dsyme 

Does this look good for the first PR? I'll put in another PR to explore supporting the missing functionality after this is merged per @dsyme's suggestion.

**Comment by dsyme** [comment]
I think this looks good.

**Comment by dsyme** [comment]
Thank you @Shmew for this contribution.

**Pull request merged**
