### PR TITLE
Rename toList and toArray to toListSynchronously and toArraySynchronously

### PR DESCRIPTION
**Pull request by blumu**

### CODE REVIEW

**Comment by blumu** [comment]
Not sure why one of the Travis build is failing. It seems unrelated to this PR.

**Comment by wilsoncg** [comment]
@blumu I'm just double checking the builds as it seems to have failed after my last merge.
I can see some travis mono version numbers have been bumped between a successful branch build test run in Dec and now failing branch build in Jan:

>hostname: ...
>version: v6.1.0 https://github.com/travis-ci/worker/tree/a6071dd64658ecf13ec3190bfb9e9ca3c8f3e10d
>hostname: ...
>version: v6.2.0 https://github.com/travis-ci/worker/tree/5e5476e01646095f48eec13196fdb3faf8f5cbf7

>Setting up mono-devel (5.18.0.225-0xamarin1+ubuntu1404b1) ...
>Setting up mono-devel (5.18.0.225-0xamarin13+ubuntu1404b1) ...
>Unpacking dotnet-runtime-deps-2.1 (2.1.6-1) ...
>Unpacking dotnet-runtime-deps-2.1 (2.1.7-1) ...
>Mono JIT compiler version 5.18.0.225 (tarball Fri Dec 21 19:40:20 UTC 2018)
>Mono JIT compiler version 5.18.0.225 (tarball Wed Jan  2 21:25:01 UTC 2019)

>Host (useful for support):
>  Version: 2.1.6
>  Commit:  3f4f8eebd8
>Host (useful for support):
>  Version: 2.1.7
>  Commit:  cca5d72d48

**Comment by dsyme** [comment]
The failure on @blumu's PR is a test failure
```
Failed   AsyncSeq.merge should fail with AggregateException if a task fails
Error Message:
   Expected: <System.AggregateException>
  But was:  <System.Exception: fail
   at AsyncSeqTests.AsyncSeq-merge should fail with AggregateException if a task fails@1252-5.Invoke(Unit unitVar) in /home/travis/build/fsprojects/FSharp.Control.AsyncSeq/tests/FSharp.Control.AsyncSeq.Tests/AsyncSeqTests.fs:line 1252
   at FSharp.Control.AsyncGenerator.delay@251.FSharp-Control-IAsyncEnumerable`1-GetEnumerator() in /home/travis/build/fsprojects/FSharp.Control.AsyncSeq/src/FSharp.Control.AsyncSeq/AsyncSeq.fs:line 252
   at FSharp.Control.AsyncGenerator.append@265-1.Invoke(Unit unitVar0) in /home/travis/build/fsprojects/FSharp.Control.AsyncSeq/src/FSharp.Control.AsyncSeq/AsyncSeq.fs:line 265
   at FSharp.Control.AsyncGenerator.FSharp-Control-AsyncGenerator-AsyncGenerator-1-Apply@188-1.Invoke(Step`1 _arg1)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
```
I think this is benign and we can just adjust or remove the test - it's not essential that we get an AggregateException

**Comment by dsyme** [comment]
@wilsoncg Note the failure is actually on .NET Core:

```
Test run for /home/travis/build/fsprojects/FSharp.Control.AsyncSeq/tests/FSharp.Control.AsyncSeq.Tests/bin/Release/netcoreapp2.0/FSharp.Control.AsyncSeq.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
Failed   AsyncSeq.merge should fail with AggregateException if a task fails
Error Message:
   Expected: <System.AggregateException>
  But was:  <System.Exception: fail
   at AsyncSeqTests.AsyncSeq-merge should fail with AggregateException if a task fails@1252-5.Invoke(Unit unitVar) in /home/travis/build/fsprojects/FSharp.Control.AsyncSeq/tests/FSharp.Control.AsyncSeq.Tests/AsyncSeqTests.fs:line 1252
```

**Comment by blumu** [comment]
@dsyme @wilsoncg Let me know if there is anything I can do to unblock this PR.

**Pull request merged**
